version: '3'
services:
    mongodb:
        image: mongo
        ports:
          - 27017:27017
    mongo-express:
        image: mongo-express
        environment:
            - ME_CONFIG_MONGODB_SERVER=mongodb
        depends_on:
            - mongodb
        ports:
          - 8081:8081